# We utilized ChatGPT to create dictionaries of common replacements based on the cuisine, healthy, vegan and others

vegan_transformations= {
    "butter": "vegan butter",
    "milk": "almond milk",
    "cream": "coconut cream",
    "cheese": "vegan cheese",
    "yogurt": "soy yogurt",
    "egg": "flax egg",
    "chicken": "tofu",
    "beef": "tempeh",
    "pork": "jackfruit",
    "fish": "tofu",
    "shrimp": "vegan shrimp",
    "lobster": "vegan lobster",
    "crab": "vegan crab",
    "honey": "agave nectar",
    "gelatin": "agar agar",
    "anchovies": "capers",
    "bacon": "tempeh bacon",
    "sausage": "vegan sausage",
    "meatballs": "vegan meatballs",
    "mayonnaise": "vegan mayonnaise",
    "sour cream": "vegan sour cream",
    "suet": "vegetable shortening",
    "bone broth": "vegetable broth",
    "whey": "rice protein",
    "casein": "soy protein",
    "lard": "vegetable shortening",
    "duck": "seitan",
    "lamb": "tempeh",
    "venison": "mushrooms",
    "goose": "tempeh",
    "turkey": "tofurkey",
    "veal": "seitan",
    "quail": "tempeh",
    "elk": "mushrooms",
    "pheasant": "tofu",
    "rabbit": "tempeh",
    "clams": "oyster mushrooms",
    "mussels": "oyster mushrooms",
    "scallops": "oyster mushrooms",
    "bison": "lentils",
    "alligator": "eggplant",
    "snake": "seitan",
    "turtle": "seitan",
    "bear": "lentils",
    "crayfish": "vegan crawfish",
    "frog legs": "oyster mushrooms",
    "escargot": "oyster mushrooms",
    "oyster sauce": "vegetarian oyster sauce"
}

vegetarian_transformations = {
    "chicken": "paneer",
    "beef": "mushrooms",
    "pork": "tofu",
    "fish": "paneer",
    "shrimp": "paneer",
    "lobster": "artichoke",
    "crab": "artichoke",
    "bacon": "tempeh bacon",
    "sausage": "vegetarian sausage",
    "meatballs": "vegetarian meatballs",
    "chicken broth": "vegetable broth",
    "beef broth": "vegetable broth",
    "fish sauce": "soy sauce",
    "anchovies": "capers",
    "gelatin": "agar agar",
    "lard": "vegetable shortening",
    "duck": "mushrooms",
    "lamb": "mushrooms",
    "venison": "mushrooms",
    "goose": "mushrooms",
    "turkey": "tofurkey",
    "veal": "mushrooms",
    "quail": "tofu",
    "elk": "mushrooms",
    "pheasant": "tofu",
    "rabbit": "tofu",
    "clams": "oyster mushrooms",
    "mussels": "oyster mushrooms",
    "scallops": "oyster mushrooms",
    "bison": "lentils",
    "alligator": "eggplant",
    "snake": "tofu",
    "turtle": "tofu",
    "bear": "lentils",
    "crayfish": "vegetarian crawfish",
    "frog legs": "oyster mushrooms",
    "escargot": "oyster mushrooms",
    "fish stock": "vegetable stock"
}

healthy_transformations = {
    "butter": "olive oil",
    "heavy cream": "Greek yogurt",
    "sour cream": "Greek yogurt",
    "cream cheese": "neufchâtel cheese",
    "mayonnaise": "avocado",
    "refined sugar": "honey",
    "flour": "whole wheat flour",
    "rice": "brown rice",
    "potatoes": "sweet potatoes",
    "ground beef": "ground turkey",
    "pork sausage": "turkey sausage",
    "bacon": "turkey bacon",
    "bread crumbs": "rolled oats",
    "chips": "carrot sticks",
    "soda": "sparkling water",
    "bread": "whole grain bread",
    "tortillas": "lettuce wraps",
    "pasta": "zucchini noodles",
    "syrup": "fruit compote",
    "canned fruit": "fresh fruit",
    "ice cream": "frozen yogurt",
    "chocolate chips": "dried fruit",
    "granola": "homemade oatmeal",
    "croutons": "toasted nuts",
    "dressing": "vinaigrette",
    "beef broth": "vegetable broth",
    "whole milk": "skim milk",
    "coconut milk": "almond milk",
    "white cheese": "feta cheese",
    "salami": "prosciutto",
    "fried food": "baked or grilled food",
    "white sugar": "coconut sugar",
    "canola oil": "extra-virgin olive oil",
    "white potatoes": "sweet potatoes",
    "flour tortillas": "whole wheat tortillas",
    "beef": "lean ground beef",
    "bacon": "turkey bacon",
    "pork chops": "chicken breast",
    "fried chicken": "baked or grilled chicken",
    "rice": "quinoa",
    "sour cream": "Greek yogurt",
    "soda": "sparkling water with fruit slices",
    "maple syrup": "honey",
    "mayonnaise": "hummus",
    "sugar": "stevia",
    "cheese": "nutritional yeast",
    "cream": "coconut cream",
    "flour": "almond flour",
    "breadcrumbs": "chia seeds",
    "pasta": "whole grain pasta",
    "hot dogs": "turkey hot dogs",
    "beef jerky": "turkey jerky",
    "sausage": "turkey sausage",
    "white bread": "whole grain bread",
    "mashed potatoes": "mashed cauliflower",
    "potato chips": "kale chips",
    "chocolate": "dark chocolate",
    "lettuce": "spinach or kale",
    "taco shells": "lettuce cups",
    "french fries": "sweet potato fries",
    "canned soup": "homemade soup",
    "canned tomatoes": "fresh tomatoes",
    "cream-based soups": "broth-based soups",
}



italian_transformations = {
    # Pasta
    "noodles": "pasta",
    "spaghetti": "linguine",
    "ramen": "fusilli",
    "udon": "penne",
    "pho": "rigatoni",
    "fettuccine": "farfalle",
    "angel hair": "capellini",
    "lasagna noodles": "cannelloni",
    "macaroni": "cavatappi",
    "ravioli": "tortellini",
    "gnocchi": "spaghetti squash",
    # Meat
    "beef": "veal",
    "pork": "prosciutto",
    "chicken": "pancetta",
    "bacon": "pancetta",
    "sausage": "soppressata",
    "ground beef": "ground pork",
    "lamb": "cotechino",
    "duck": "guanciale",
    "turkey": "mortadella",
    # Seafood
    "shrimp": "scallops",
    "crab": "lobster",
    "salmon": "swordfish",
    "tuna": "halibut",
    "clams": "mussels",
    "octopus": "squid",
    # Cheese
    "cheddar cheese": "parmesan cheese",
    "monterey jack cheese": "mozzarella cheese",
    "cream cheese": "ricotta cheese",
    "goat cheese": "gorgonzola cheese",
    "feta cheese": "pecorino cheese",
    "blue cheese": "fontina cheese",
    "brie cheese": "taleggio cheese",
    "gouda cheese": "provolone cheese",
    # Vegetables
    "cabbage": "radicchio",
    "carrots": "zucchini",
    "spinach": "arugula",
    "bean sprouts": "cherry tomatoes",
    "asparagus": "fava beans",
    "broccoli": "broccolini",
    "cauliflower": "romanesco",
    "bell pepper": "chili pepper",
    "corn": "fava beans",
    "peas": "green beans",
    # Other
    "soy sauce": "balsamic vinegar",
    "sriracha": "red pepper flakes",
    "teriyaki sauce": "olive oil",
    "wasabi": "horseradish",
    "tortilla chips": "bread crumbs",
    "hoisin sauce": "molasses",
    "oyster sauce": "anchovy paste",
    "fish sauce": "white wine",
    "mirin": "sherry",
    "sake": "marsala",
    "cornstarch": "flour",
    "brown sugar": "honey",
    "coconut milk": "heavy cream",
    "tamarind paste": "lemon juice",
    "saffron": "paprika"
}


mexican_transformations = {
    # Protein
    "beef": "carne asada",
    "pork": "carnitas",
    "bacon": "chorizo",
    "sausage": "chorizo",
    "ground beef": "picadillo",
    "lamb": "barbacoa",
    "duck": "pato",
    "turkey": "pavo",
    "ham": "jamón serrano",
    "chicken": "shredded chicken",
    "chorizo": "soyrizo",
    "ground turkey": "ground chicken",
    "shrimp": "tofu",
    "fish fillets": "tofu",
    "steak": "portobello mushrooms",
    # Vegetables
    "bell pepper": "poblano pepper",
    "tomatoes": "tomatillos",
    "onion": "red onion",
    "jalapenos": "serrano peppers",
    "corn": "hominy",
    "black beans": "pinto beans",
    "cabbage": "radicchio",
    "carrots": "jicama",
    "lettuce": "romaine lettuce",
    "cilantro": "epazote",
    # Dairy
    "cheddar cheese": "cotija cheese",
    "monterey jack cheese": "queso blanco",
    "sour cream": "crema",
    "cream cheese": "queso fresco",
    "yogurt": "crema",
    # Herbs and Spices
    "oregano": "paprika",
    "thyme": "cumin",
    "rosemary": "coriander",
    "basil": "epazote",
    "bay leaves": "hoja santa",
    "cayenne pepper": "chipotle powder",
    "chili powder": "ancho chili powder",
    "garlic powder": "granulated garlic",
    "onion powder": "granulated onion",
    "paprika": "smoked paprika",
    "red pepper flakes": "dried ancho chilies",
    "turmeric": "achiote",
    "vanilla extract": "cinnamon",
    "cinnamon": "Mexican cinnamon",
    # Other
    "butter": "olive oil",
    "flour": "masa harina",
    "bread crumbs": "tortilla chips",
    "white wine": "tequila",
    "soy sauce": "mole",
    "teriyaki sauce": "adobo sauce",
    "hoisin sauce": "piloncillo",
    "mirin": "lime juice",
    "sake": "mezcal",
    "cornstarch": "cornmeal",
    "brown sugar": "piloncillo",
    "coconut milk": "crema de coco",
    "tamarind paste": "dried hibiscus flowers",
    "saffron": "achiote"
}


unhealthy_transformations = {
    "butter": "margarine",
    "beef": "ground beef",
    "chicken": "fried chicken",
    "cheese": "processed cheese",
    "pasta": "instant ramen",
    "sugar": "high-fructose corn syrup",
    "flour": "cake flour",
    "rice": "instant rice",
    "potatoes": "tater tots",
    "mayonnaise": "miracle whip",
    "bread": "white bread",
    "chips": "cheese puffs",
    "soda": "energy drinks",
    "ice cream": "frozen dessert",
    "salad dressing": "creamy dressing",
    "milk": "whole milk",
    "bacon": "processed bacon",
    "sausage": "processed sausage",
    "granola": "sugary cereal",
    "croutons": "fried onions",
    "beef broth": "canned broth",
    "coconut milk": "sweetened condensed milk",
    "cheese dip": "queso dip",
    "chocolate": "chocolate bars",
    "peanut butter": "cookie butter",
    "honey": "corn syrup",
    "beef jerky": "processed meat snacks",
    "fruit juice": "fruit-flavored drinks",
    "olive oil": "vegetable oil",
    "ground turkey": "ground beef",
    "turkey bacon": "regular bacon",
    "almond milk": "whole milk",
    "sweet potatoes": "french fries",
    "oatmeal": "sugar cereal",
    "brown rice": "white rice",
    "sparkling water": "soda",
    "whole wheat bread": "white bread",
    "lettuce wraps": "tortillas",
    "avocado": "mayonnaise",
    "Greek yogurt": "sour cream",
    "neufchâtel cheese": "cream cheese",
    "rolled oats": "bread crumbs",
    "carrot sticks": "potato chips",
    "vegetable broth": "beef broth",
    "skim milk": "whole milk",
    "feta cheese": "cheddar cheese",
    "prosciutto": "turkey deli meat",
    "baked/grilled food": "fried food",
    "whole grain pasta": "white pasta",
    "fruit compote": "syrup",
    "fresh fruit": "canned fruit in syrup",
    "dried fruit": "chocolate chips",
    "toasted nuts": "croutons",
    "vinaigrette": "mayonnaise-based dressing",
    "oil and vinegar dressing": "creamy salad dressing"
}



vegan_protein_content = {
    "vegan butter": {"protein_content": 0, "unit": "g", "unit_per": "serving"},
    "almond milk": {"protein_content": 1, "unit": "g", "unit_per": "cup"},
    "coconut cream": {"protein_content": 1, "unit": "g", "unit_per": "cup"},
    "vegan cheese": {"protein_content": 7, "unit": "g", "unit_per": "ounce"},
    "soy yogurt": {"protein_content": 6, "unit": "g", "unit_per": "ounce"},
    "flax egg": {"protein_content": 2, "unit": "g", "unit_per": "large egg"},
    "tofu": {"protein_content": 10, "unit": "g", "unit_per": "3 oz"},
    "tempeh": {"protein_content": 16, "unit": "g", "unit_per": "3 oz"},
    "jackfruit": {"protein_content": 1, "unit": "g", "unit_per": "cup"},
    "vegan shrimp": {"protein_content": 10, "unit": "g", "unit_per": "3 oz"},
    "vegan lobster": {"protein_content": 10, "unit": "g", "unit_per": "3 oz"},
    "vegan crab": {"protein_content": 10, "unit": "g", "unit_per": "3 oz"},
    "agave nectar": {"protein_content": 0, "unit": "g", "unit_per": "tbsp"},
    "agar agar": {"protein_content": 0, "unit": "g", "unit_per": "tbsp"},
    "capers": {"protein_content": 1, "unit": "g", "unit_per": "tbsp"},
    "tempeh bacon": {"protein_content": 8, "unit": "g", "unit_per": "2 slices"},
    "vegan sausage": {"protein_content": 15, "unit": "g", "unit_per": "2 links"},
    "vegan meatballs": {"protein_content": 15, "unit": "g", "unit_per": "3 meatballs"},
    "vegan mayonnaise": {"protein_content": 0, "unit": "g", "unit_per": "tbsp"},
    "vegan sour cream": {"protein_content": 0, "unit": "g", "unit_per": "tbsp"},
    "vegetable shortening": {"protein_content": 0, "unit": "g", "unit_per": "tbsp"},
    "vegetable broth": {"protein_content": 0, "unit": "g", "unit_per": "cup"},
    "rice protein": {"protein_content": 24, "unit": "g", "unit_per": "serving"},
    "soy protein": {"protein_content": 27, "unit": "g", "unit_per": "serving"},
    "seitan": {"protein_content": 25, "unit": "g", "unit_per": "3 oz"},
    "mushrooms": {"protein_content": 2, "unit": "g", "unit_per": "cup"},
    "tofurkey": {"protein_content": 13, "unit": "g", "unit_per": "3 oz"},
    "lentils": {"protein_content": 9, "unit": "g", "unit_per": "cup"},
    "lamb": {"protein_content": 19.7, "protein_unit": "g", "unit_per": "100g serving"},
    "venison": {"protein_content": 21.8, "protein_unit": "g", "unit_per": "100g serving"},
    "goose": {"protein_content": 21.8, "protein_unit": "g", "unit_per": "100g serving"},
    "turkey": {"protein_content": 29.6, "protein_unit": "g", "unit_per": "100g serving"},
    "veal": {"protein_content": 36.6, "protein_unit": "g", "unit_per": "100g serving"},
    "quail": {"protein_content": 21.9, "protein_unit": "g", "unit_per": "100g serving"},
    "elk": {"protein_content": 21.4, "protein_unit": "g", "unit_per": "100g serving"},
    "pheasant": {"protein_content": 27.6, "protein_unit": "g", "unit_per": "100g serving"},
    "rabbit": {"protein_content": 21.7, "protein_unit": "g", "unit_per": "100g serving"},
    "clams": {"protein_content": 11.9, "protein_unit": "g", "unit_per": "100g serving"},
    "mussels": {"protein_content": 18.0, "protein_unit": "g", "unit_per": "100g serving"},
    "scallops": {"protein_content": 19.0, "protein_unit": "g", "unit_per": "100g serving"},
    "bison": {"protein_content": 22.8, "protein_unit": "g", "unit_per": "100g serving"},
    "alligator": {"protein_content": 21.8, "protein_unit": "g", "unit_per": "100g serving"},
    "snake": {"protein_content": 17.0, "protein_unit": "g", "unit_per": "100g serving"},
    "turtle": {"protein_content": 19.0, "protein_unit": "g", "unit_per": "100g serving"},
    "bear": {"protein_content": 19.1, "protein_unit": "g", "unit_per": "100g serving"},
    "crayfish": {"protein_content": 14.8, "protein_unit": "g", "unit_per": "100g serving"},
    "frog legs": {"protein_content": 16.4, "protein_unit": "g", "unit_per": "100g serving"},
    "escargot": {"protein_content": 16.1, "protein_unit": "g", "unit_per": "100g serving"},
    "oyster sauce": {"protein_content": 0.7, "protein_unit": "g", "unit_per": "tablespoon"}}

def reverse_dict(d):
    new_dict = {}
    for key, value in d.items():
        new_dict[value] = key
    return new_dict

non_vegetarian_transformations = reverse_dict(vegetarian_transformations)

vegetarian_dict = {
    "paneer": {
        "protein_content": 18,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "mushrooms": {
        "protein_content": 3.1,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "tofu": {
        "protein_content": 8.1,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "artichoke": {
        "protein_content": 3.3,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "tempeh bacon": {
        "protein_content": 16,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetarian sausage": {
        "protein_content": 17,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetarian meatballs": {
        "protein_content": 14,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetable broth": {
        "protein_content": 0.9,
        "protein_unit": "grams",
        "unit_per": "100 milliliters"
    },
    "soy sauce": {
        "protein_content": 6,
        "protein_unit": "grams",
        "unit_per": "100 milliliters"
    },
    "capers": {
        "protein_content": 2.4,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "agar agar": {
        "protein_content": 0.5,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetable shortening": {
        "protein_content": 0,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "oyster mushrooms": {
        "protein_content": 3.3,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "tofurkey": {
        "protein_content": 13,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetarian crawfish": {
        "protein_content": 14,
        "protein_unit": "grams",
        "unit_per": "100 grams"
    },
    "vegetable stock": {
        "protein_content": 0.5,
        "protein_unit": "grams",
        "unit_per": "100 milliliters"
    }
}

sugars = ["granulated sugar", "brown sugar", "powdered sugar", "honey", "maple syrup", "corn syrup", "molasses", "agave nectar"]

sugar_substitutes = ["stevia", "monk fruit sweetener", "erythritol", "xylitol", "coconut sugar", "date sugar", "brown rice syrup", "maple sugar", "raw honey", "molasses", "fruit juice concentrate", "apple sauce", "ripe mashed bananas"]

